#***************************************************************
# Name:     	Luan Nguyen
# username:     masc0638
# Class:     	CS530, Spring 2015
# Project:     	Assignment 3
# File:        	Makefile
# Note:        	Makefile to compile myParser.c
#****************************************************************

parse:
    cc myParser.c -o parse

clean:
    rm -f a.out core parse
